name: "Website Simple Healthcheck"
description: "Website status checking and text scanning"
branding:
  icon: activity
  color: white
inputs:
  web-url:
    description: "Specify the URL to scan"
    required: true
runs:
  using: "composite"
  steps:
    - run: echo Pinging ${{ inputs.web-url }}
      shell: bash
    - run: chmod +x ${{ github.action_path }}/scan-website.sh
      shell: bash
    - run: ${{ github.action_path }}/scan-website.sh ${{ inputs.web-url }}
      shell: bash
